In [2]:
set1:set = {1,3,5,6,7,8,1,1,10}
set1.add(23)
set1

{1, 3, 5, 6, 7, 8, 10, 23}

In [7]:
import numpy as np
array1:np.ndarray = np.array(range(1,11))
array1 + 10 * 50

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [10]:
display( np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))


array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [14]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))


array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

0.4619082590202097

array([[[-1.32416711e+00,  5.01568962e-01,  1.22825320e-01],
        [ 6.18838411e-01, -1.16961632e-01,  1.00472852e+00],
        [ 3.20664651e-01, -8.26742124e-01, -1.30219968e+00],
        [ 9.75213487e-01,  9.55361495e-01,  1.99606085e-01],
        [ 8.56498756e-02, -1.47563687e+00, -3.57915171e-01]],

       [[-2.95443005e-01, -2.75072937e+00, -4.55507726e-01],
        [-1.24584537e+00,  4.49853327e-01, -2.28143646e-01],
        [ 6.64433075e-01,  3.34882081e-01, -2.57459269e-01],
        [-3.68467473e-02,  8.01481087e-01,  1.67742700e+00],
        [ 1.71660369e-01, -1.18037879e-01, -1.33411063e+00]],

       [[ 3.36206033e-01,  4.35572919e-01, -5.91130116e-01],
        [-7.02124496e-01,  3.10654448e-01,  1.36689862e+00],
        [ 8.88415911e-01,  1.90526579e-03, -1.82695585e-02],
        [-2.13929078e-01, -7.43304306e-01, -3.51467904e-01],
        [ 2.10621469e+00,  1.37128833e+00,  2.14641430e+00]],

       [[-3.16990958e-01,  1.70404364e+00,  1.58000747e+00],
        [-7.601184

array([[5, 1, 8, 2, 4],
       [4, 8, 2, 3, 5],
       [6, 7, 4, 1, 5],
       [9, 3, 1, 8, 1],
       [3, 7, 6, 9, 4],
       [2, 6, 9, 8, 2],
       [9, 6, 1, 1, 1],
       [2, 3, 4, 1, 9],
       [3, 2, 1, 5, 6],
       [6, 1, 5, 4, 2]])